name: CI
on: [push]
jobs:
  publish-hidora:
    name: Deploy to Docker Hub & Hidora
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: httptoolkit/anonymizing-reverse-proxy
          tags: |
            type=raw,value=prod,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build & deploy to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Redeploy site
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          sleep 30 # Wait for Docker Hub to fully publish

          # Trigger a container redeploy:
          curl "https://app.hidora.com/1.0/environment/control/rest/redeploycontainersbygroup?session=$HIDORA_API_TOKEN&envName=htk-anonymizing-reverse-proxy&nodeGroup=cp&tag=prod&useExistingVolumes=true" | \
             tee /dev/stderr | \
             grep -q 'Node has been successfully updated'
        env:
          HIDORA_API_TOKEN: ${{ secrets.HIDORA_API_TOKEN }}